// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: spec.proto

package boa.types;

public final class Spec {
  private Spec() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface SpecificationOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required bool is_exceptional = 1;
    /**
     * <code>required bool is_exceptional = 1;</code>
     */
    boolean hasIsExceptional();
    /**
     * <code>required bool is_exceptional = 1;</code>
     */
    boolean getIsExceptional();

    // repeated .boa.types.Expression preconditions = 2;
    /**
     * <code>repeated .boa.types.Expression preconditions = 2;</code>
     */
    java.util.List<boa.types.Ast.Expression> 
        getPreconditionsList();
    /**
     * <code>repeated .boa.types.Expression preconditions = 2;</code>
     */
    boa.types.Ast.Expression getPreconditions(int index);
    /**
     * <code>repeated .boa.types.Expression preconditions = 2;</code>
     */
    int getPreconditionsCount();
    /**
     * <code>repeated .boa.types.Expression preconditions = 2;</code>
     */
    java.util.List<? extends boa.types.Ast.ExpressionOrBuilder> 
        getPreconditionsOrBuilderList();
    /**
     * <code>repeated .boa.types.Expression preconditions = 2;</code>
     */
    boa.types.Ast.ExpressionOrBuilder getPreconditionsOrBuilder(
        int index);

    // repeated .boa.types.Expression postconditions = 3;
    /**
     * <code>repeated .boa.types.Expression postconditions = 3;</code>
     */
    java.util.List<boa.types.Ast.Expression> 
        getPostconditionsList();
    /**
     * <code>repeated .boa.types.Expression postconditions = 3;</code>
     */
    boa.types.Ast.Expression getPostconditions(int index);
    /**
     * <code>repeated .boa.types.Expression postconditions = 3;</code>
     */
    int getPostconditionsCount();
    /**
     * <code>repeated .boa.types.Expression postconditions = 3;</code>
     */
    java.util.List<? extends boa.types.Ast.ExpressionOrBuilder> 
        getPostconditionsOrBuilderList();
    /**
     * <code>repeated .boa.types.Expression postconditions = 3;</code>
     */
    boa.types.Ast.ExpressionOrBuilder getPostconditionsOrBuilder(
        int index);

    // repeated string assignable_fields = 4;
    /**
     * <code>repeated string assignable_fields = 4;</code>
     */
    java.util.List<java.lang.String>
    getAssignableFieldsList();
    /**
     * <code>repeated string assignable_fields = 4;</code>
     */
    int getAssignableFieldsCount();
    /**
     * <code>repeated string assignable_fields = 4;</code>
     */
    java.lang.String getAssignableFields(int index);
    /**
     * <code>repeated string assignable_fields = 4;</code>
     */
    com.google.protobuf.ByteString
        getAssignableFieldsBytes(int index);

    // repeated string exception_types = 5;
    /**
     * <code>repeated string exception_types = 5;</code>
     */
    java.util.List<java.lang.String>
    getExceptionTypesList();
    /**
     * <code>repeated string exception_types = 5;</code>
     */
    int getExceptionTypesCount();
    /**
     * <code>repeated string exception_types = 5;</code>
     */
    java.lang.String getExceptionTypes(int index);
    /**
     * <code>repeated string exception_types = 5;</code>
     */
    com.google.protobuf.ByteString
        getExceptionTypesBytes(int index);
  }
  /**
   * Protobuf type {@code boa.types.Specification}
   */
  public static final class Specification extends
      com.google.protobuf.GeneratedMessage
      implements SpecificationOrBuilder {
    // Use Specification.newBuilder() to construct.
    private Specification(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Specification(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Specification defaultInstance;
    public static Specification getDefaultInstance() {
      return defaultInstance;
    }

    public Specification getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Specification(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              isExceptional_ = input.readBool();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                preconditions_ = new java.util.ArrayList<boa.types.Ast.Expression>();
                mutable_bitField0_ |= 0x00000002;
              }
              preconditions_.add(input.readMessage(boa.types.Ast.Expression.PARSER, extensionRegistry));
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                postconditions_ = new java.util.ArrayList<boa.types.Ast.Expression>();
                mutable_bitField0_ |= 0x00000004;
              }
              postconditions_.add(input.readMessage(boa.types.Ast.Expression.PARSER, extensionRegistry));
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                assignableFields_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000008;
              }
              assignableFields_.add(input.readBytes());
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                exceptionTypes_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000010;
              }
              exceptionTypes_.add(input.readBytes());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          preconditions_ = java.util.Collections.unmodifiableList(preconditions_);
        }
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          postconditions_ = java.util.Collections.unmodifiableList(postconditions_);
        }
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          assignableFields_ = new com.google.protobuf.UnmodifiableLazyStringList(assignableFields_);
        }
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          exceptionTypes_ = new com.google.protobuf.UnmodifiableLazyStringList(exceptionTypes_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return boa.types.Spec.internal_static_boa_types_Specification_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return boa.types.Spec.internal_static_boa_types_Specification_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              boa.types.Spec.Specification.class, boa.types.Spec.Specification.Builder.class);
    }

    public static com.google.protobuf.Parser<Specification> PARSER =
        new com.google.protobuf.AbstractParser<Specification>() {
      public Specification parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Specification(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Specification> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required bool is_exceptional = 1;
    public static final int IS_EXCEPTIONAL_FIELD_NUMBER = 1;
    private boolean isExceptional_;
    /**
     * <code>required bool is_exceptional = 1;</code>
     */
    public boolean hasIsExceptional() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required bool is_exceptional = 1;</code>
     */
    public boolean getIsExceptional() {
      return isExceptional_;
    }

    // repeated .boa.types.Expression preconditions = 2;
    public static final int PRECONDITIONS_FIELD_NUMBER = 2;
    private java.util.List<boa.types.Ast.Expression> preconditions_;
    /**
     * <code>repeated .boa.types.Expression preconditions = 2;</code>
     */
    public java.util.List<boa.types.Ast.Expression> getPreconditionsList() {
      return preconditions_;
    }
    /**
     * <code>repeated .boa.types.Expression preconditions = 2;</code>
     */
    public java.util.List<? extends boa.types.Ast.ExpressionOrBuilder> 
        getPreconditionsOrBuilderList() {
      return preconditions_;
    }
    /**
     * <code>repeated .boa.types.Expression preconditions = 2;</code>
     */
    public int getPreconditionsCount() {
      return preconditions_.size();
    }
    /**
     * <code>repeated .boa.types.Expression preconditions = 2;</code>
     */
    public boa.types.Ast.Expression getPreconditions(int index) {
      return preconditions_.get(index);
    }
    /**
     * <code>repeated .boa.types.Expression preconditions = 2;</code>
     */
    public boa.types.Ast.ExpressionOrBuilder getPreconditionsOrBuilder(
        int index) {
      return preconditions_.get(index);
    }

    // repeated .boa.types.Expression postconditions = 3;
    public static final int POSTCONDITIONS_FIELD_NUMBER = 3;
    private java.util.List<boa.types.Ast.Expression> postconditions_;
    /**
     * <code>repeated .boa.types.Expression postconditions = 3;</code>
     */
    public java.util.List<boa.types.Ast.Expression> getPostconditionsList() {
      return postconditions_;
    }
    /**
     * <code>repeated .boa.types.Expression postconditions = 3;</code>
     */
    public java.util.List<? extends boa.types.Ast.ExpressionOrBuilder> 
        getPostconditionsOrBuilderList() {
      return postconditions_;
    }
    /**
     * <code>repeated .boa.types.Expression postconditions = 3;</code>
     */
    public int getPostconditionsCount() {
      return postconditions_.size();
    }
    /**
     * <code>repeated .boa.types.Expression postconditions = 3;</code>
     */
    public boa.types.Ast.Expression getPostconditions(int index) {
      return postconditions_.get(index);
    }
    /**
     * <code>repeated .boa.types.Expression postconditions = 3;</code>
     */
    public boa.types.Ast.ExpressionOrBuilder getPostconditionsOrBuilder(
        int index) {
      return postconditions_.get(index);
    }

    // repeated string assignable_fields = 4;
    public static final int ASSIGNABLE_FIELDS_FIELD_NUMBER = 4;
    private com.google.protobuf.LazyStringList assignableFields_;
    /**
     * <code>repeated string assignable_fields = 4;</code>
     */
    public java.util.List<java.lang.String>
        getAssignableFieldsList() {
      return assignableFields_;
    }
    /**
     * <code>repeated string assignable_fields = 4;</code>
     */
    public int getAssignableFieldsCount() {
      return assignableFields_.size();
    }
    /**
     * <code>repeated string assignable_fields = 4;</code>
     */
    public java.lang.String getAssignableFields(int index) {
      return assignableFields_.get(index);
    }
    /**
     * <code>repeated string assignable_fields = 4;</code>
     */
    public com.google.protobuf.ByteString
        getAssignableFieldsBytes(int index) {
      return assignableFields_.getByteString(index);
    }

    // repeated string exception_types = 5;
    public static final int EXCEPTION_TYPES_FIELD_NUMBER = 5;
    private com.google.protobuf.LazyStringList exceptionTypes_;
    /**
     * <code>repeated string exception_types = 5;</code>
     */
    public java.util.List<java.lang.String>
        getExceptionTypesList() {
      return exceptionTypes_;
    }
    /**
     * <code>repeated string exception_types = 5;</code>
     */
    public int getExceptionTypesCount() {
      return exceptionTypes_.size();
    }
    /**
     * <code>repeated string exception_types = 5;</code>
     */
    public java.lang.String getExceptionTypes(int index) {
      return exceptionTypes_.get(index);
    }
    /**
     * <code>repeated string exception_types = 5;</code>
     */
    public com.google.protobuf.ByteString
        getExceptionTypesBytes(int index) {
      return exceptionTypes_.getByteString(index);
    }

    private void initFields() {
      isExceptional_ = false;
      preconditions_ = java.util.Collections.emptyList();
      postconditions_ = java.util.Collections.emptyList();
      assignableFields_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      exceptionTypes_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasIsExceptional()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getPreconditionsCount(); i++) {
        if (!getPreconditions(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      for (int i = 0; i < getPostconditionsCount(); i++) {
        if (!getPostconditions(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBool(1, isExceptional_);
      }
      for (int i = 0; i < preconditions_.size(); i++) {
        output.writeMessage(2, preconditions_.get(i));
      }
      for (int i = 0; i < postconditions_.size(); i++) {
        output.writeMessage(3, postconditions_.get(i));
      }
      for (int i = 0; i < assignableFields_.size(); i++) {
        output.writeBytes(4, assignableFields_.getByteString(i));
      }
      for (int i = 0; i < exceptionTypes_.size(); i++) {
        output.writeBytes(5, exceptionTypes_.getByteString(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, isExceptional_);
      }
      for (int i = 0; i < preconditions_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, preconditions_.get(i));
      }
      for (int i = 0; i < postconditions_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, postconditions_.get(i));
      }
      {
        int dataSize = 0;
        for (int i = 0; i < assignableFields_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(assignableFields_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getAssignableFieldsList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < exceptionTypes_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(exceptionTypes_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getExceptionTypesList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static boa.types.Spec.Specification parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static boa.types.Spec.Specification parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static boa.types.Spec.Specification parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static boa.types.Spec.Specification parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static boa.types.Spec.Specification parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static boa.types.Spec.Specification parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static boa.types.Spec.Specification parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static boa.types.Spec.Specification parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static boa.types.Spec.Specification parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static boa.types.Spec.Specification parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(boa.types.Spec.Specification prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code boa.types.Specification}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements boa.types.Spec.SpecificationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return boa.types.Spec.internal_static_boa_types_Specification_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return boa.types.Spec.internal_static_boa_types_Specification_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                boa.types.Spec.Specification.class, boa.types.Spec.Specification.Builder.class);
      }

      // Construct using boa.types.Spec.Specification.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getPreconditionsFieldBuilder();
          getPostconditionsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        isExceptional_ = false;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (preconditionsBuilder_ == null) {
          preconditions_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          preconditionsBuilder_.clear();
        }
        if (postconditionsBuilder_ == null) {
          postconditions_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          postconditionsBuilder_.clear();
        }
        assignableFields_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        exceptionTypes_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return boa.types.Spec.internal_static_boa_types_Specification_descriptor;
      }

      public boa.types.Spec.Specification getDefaultInstanceForType() {
        return boa.types.Spec.Specification.getDefaultInstance();
      }

      public boa.types.Spec.Specification build() {
        boa.types.Spec.Specification result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public boa.types.Spec.Specification buildPartial() {
        boa.types.Spec.Specification result = new boa.types.Spec.Specification(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.isExceptional_ = isExceptional_;
        if (preconditionsBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            preconditions_ = java.util.Collections.unmodifiableList(preconditions_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.preconditions_ = preconditions_;
        } else {
          result.preconditions_ = preconditionsBuilder_.build();
        }
        if (postconditionsBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            postconditions_ = java.util.Collections.unmodifiableList(postconditions_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.postconditions_ = postconditions_;
        } else {
          result.postconditions_ = postconditionsBuilder_.build();
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          assignableFields_ = new com.google.protobuf.UnmodifiableLazyStringList(
              assignableFields_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.assignableFields_ = assignableFields_;
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          exceptionTypes_ = new com.google.protobuf.UnmodifiableLazyStringList(
              exceptionTypes_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.exceptionTypes_ = exceptionTypes_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof boa.types.Spec.Specification) {
          return mergeFrom((boa.types.Spec.Specification)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(boa.types.Spec.Specification other) {
        if (other == boa.types.Spec.Specification.getDefaultInstance()) return this;
        if (other.hasIsExceptional()) {
          setIsExceptional(other.getIsExceptional());
        }
        if (preconditionsBuilder_ == null) {
          if (!other.preconditions_.isEmpty()) {
            if (preconditions_.isEmpty()) {
              preconditions_ = other.preconditions_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensurePreconditionsIsMutable();
              preconditions_.addAll(other.preconditions_);
            }
            onChanged();
          }
        } else {
          if (!other.preconditions_.isEmpty()) {
            if (preconditionsBuilder_.isEmpty()) {
              preconditionsBuilder_.dispose();
              preconditionsBuilder_ = null;
              preconditions_ = other.preconditions_;
              bitField0_ = (bitField0_ & ~0x00000002);
              preconditionsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getPreconditionsFieldBuilder() : null;
            } else {
              preconditionsBuilder_.addAllMessages(other.preconditions_);
            }
          }
        }
        if (postconditionsBuilder_ == null) {
          if (!other.postconditions_.isEmpty()) {
            if (postconditions_.isEmpty()) {
              postconditions_ = other.postconditions_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensurePostconditionsIsMutable();
              postconditions_.addAll(other.postconditions_);
            }
            onChanged();
          }
        } else {
          if (!other.postconditions_.isEmpty()) {
            if (postconditionsBuilder_.isEmpty()) {
              postconditionsBuilder_.dispose();
              postconditionsBuilder_ = null;
              postconditions_ = other.postconditions_;
              bitField0_ = (bitField0_ & ~0x00000004);
              postconditionsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getPostconditionsFieldBuilder() : null;
            } else {
              postconditionsBuilder_.addAllMessages(other.postconditions_);
            }
          }
        }
        if (!other.assignableFields_.isEmpty()) {
          if (assignableFields_.isEmpty()) {
            assignableFields_ = other.assignableFields_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureAssignableFieldsIsMutable();
            assignableFields_.addAll(other.assignableFields_);
          }
          onChanged();
        }
        if (!other.exceptionTypes_.isEmpty()) {
          if (exceptionTypes_.isEmpty()) {
            exceptionTypes_ = other.exceptionTypes_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureExceptionTypesIsMutable();
            exceptionTypes_.addAll(other.exceptionTypes_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasIsExceptional()) {
          
          return false;
        }
        for (int i = 0; i < getPreconditionsCount(); i++) {
          if (!getPreconditions(i).isInitialized()) {
            
            return false;
          }
        }
        for (int i = 0; i < getPostconditionsCount(); i++) {
          if (!getPostconditions(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        boa.types.Spec.Specification parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (boa.types.Spec.Specification) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required bool is_exceptional = 1;
      private boolean isExceptional_ ;
      /**
       * <code>required bool is_exceptional = 1;</code>
       */
      public boolean hasIsExceptional() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required bool is_exceptional = 1;</code>
       */
      public boolean getIsExceptional() {
        return isExceptional_;
      }
      /**
       * <code>required bool is_exceptional = 1;</code>
       */
      public Builder setIsExceptional(boolean value) {
        bitField0_ |= 0x00000001;
        isExceptional_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool is_exceptional = 1;</code>
       */
      public Builder clearIsExceptional() {
        bitField0_ = (bitField0_ & ~0x00000001);
        isExceptional_ = false;
        onChanged();
        return this;
      }

      // repeated .boa.types.Expression preconditions = 2;
      private java.util.List<boa.types.Ast.Expression> preconditions_ =
        java.util.Collections.emptyList();
      private void ensurePreconditionsIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          preconditions_ = new java.util.ArrayList<boa.types.Ast.Expression>(preconditions_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          boa.types.Ast.Expression, boa.types.Ast.Expression.Builder, boa.types.Ast.ExpressionOrBuilder> preconditionsBuilder_;

      /**
       * <code>repeated .boa.types.Expression preconditions = 2;</code>
       */
      public java.util.List<boa.types.Ast.Expression> getPreconditionsList() {
        if (preconditionsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(preconditions_);
        } else {
          return preconditionsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .boa.types.Expression preconditions = 2;</code>
       */
      public int getPreconditionsCount() {
        if (preconditionsBuilder_ == null) {
          return preconditions_.size();
        } else {
          return preconditionsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .boa.types.Expression preconditions = 2;</code>
       */
      public boa.types.Ast.Expression getPreconditions(int index) {
        if (preconditionsBuilder_ == null) {
          return preconditions_.get(index);
        } else {
          return preconditionsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .boa.types.Expression preconditions = 2;</code>
       */
      public Builder setPreconditions(
          int index, boa.types.Ast.Expression value) {
        if (preconditionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePreconditionsIsMutable();
          preconditions_.set(index, value);
          onChanged();
        } else {
          preconditionsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .boa.types.Expression preconditions = 2;</code>
       */
      public Builder setPreconditions(
          int index, boa.types.Ast.Expression.Builder builderForValue) {
        if (preconditionsBuilder_ == null) {
          ensurePreconditionsIsMutable();
          preconditions_.set(index, builderForValue.build());
          onChanged();
        } else {
          preconditionsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .boa.types.Expression preconditions = 2;</code>
       */
      public Builder addPreconditions(boa.types.Ast.Expression value) {
        if (preconditionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePreconditionsIsMutable();
          preconditions_.add(value);
          onChanged();
        } else {
          preconditionsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .boa.types.Expression preconditions = 2;</code>
       */
      public Builder addPreconditions(
          int index, boa.types.Ast.Expression value) {
        if (preconditionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePreconditionsIsMutable();
          preconditions_.add(index, value);
          onChanged();
        } else {
          preconditionsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .boa.types.Expression preconditions = 2;</code>
       */
      public Builder addPreconditions(
          boa.types.Ast.Expression.Builder builderForValue) {
        if (preconditionsBuilder_ == null) {
          ensurePreconditionsIsMutable();
          preconditions_.add(builderForValue.build());
          onChanged();
        } else {
          preconditionsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .boa.types.Expression preconditions = 2;</code>
       */
      public Builder addPreconditions(
          int index, boa.types.Ast.Expression.Builder builderForValue) {
        if (preconditionsBuilder_ == null) {
          ensurePreconditionsIsMutable();
          preconditions_.add(index, builderForValue.build());
          onChanged();
        } else {
          preconditionsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .boa.types.Expression preconditions = 2;</code>
       */
      public Builder addAllPreconditions(
          java.lang.Iterable<? extends boa.types.Ast.Expression> values) {
        if (preconditionsBuilder_ == null) {
          ensurePreconditionsIsMutable();
          super.addAll(values, preconditions_);
          onChanged();
        } else {
          preconditionsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .boa.types.Expression preconditions = 2;</code>
       */
      public Builder clearPreconditions() {
        if (preconditionsBuilder_ == null) {
          preconditions_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          preconditionsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .boa.types.Expression preconditions = 2;</code>
       */
      public Builder removePreconditions(int index) {
        if (preconditionsBuilder_ == null) {
          ensurePreconditionsIsMutable();
          preconditions_.remove(index);
          onChanged();
        } else {
          preconditionsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .boa.types.Expression preconditions = 2;</code>
       */
      public boa.types.Ast.Expression.Builder getPreconditionsBuilder(
          int index) {
        return getPreconditionsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .boa.types.Expression preconditions = 2;</code>
       */
      public boa.types.Ast.ExpressionOrBuilder getPreconditionsOrBuilder(
          int index) {
        if (preconditionsBuilder_ == null) {
          return preconditions_.get(index);  } else {
          return preconditionsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .boa.types.Expression preconditions = 2;</code>
       */
      public java.util.List<? extends boa.types.Ast.ExpressionOrBuilder> 
           getPreconditionsOrBuilderList() {
        if (preconditionsBuilder_ != null) {
          return preconditionsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(preconditions_);
        }
      }
      /**
       * <code>repeated .boa.types.Expression preconditions = 2;</code>
       */
      public boa.types.Ast.Expression.Builder addPreconditionsBuilder() {
        return getPreconditionsFieldBuilder().addBuilder(
            boa.types.Ast.Expression.getDefaultInstance());
      }
      /**
       * <code>repeated .boa.types.Expression preconditions = 2;</code>
       */
      public boa.types.Ast.Expression.Builder addPreconditionsBuilder(
          int index) {
        return getPreconditionsFieldBuilder().addBuilder(
            index, boa.types.Ast.Expression.getDefaultInstance());
      }
      /**
       * <code>repeated .boa.types.Expression preconditions = 2;</code>
       */
      public java.util.List<boa.types.Ast.Expression.Builder> 
           getPreconditionsBuilderList() {
        return getPreconditionsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          boa.types.Ast.Expression, boa.types.Ast.Expression.Builder, boa.types.Ast.ExpressionOrBuilder> 
          getPreconditionsFieldBuilder() {
        if (preconditionsBuilder_ == null) {
          preconditionsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              boa.types.Ast.Expression, boa.types.Ast.Expression.Builder, boa.types.Ast.ExpressionOrBuilder>(
                  preconditions_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          preconditions_ = null;
        }
        return preconditionsBuilder_;
      }

      // repeated .boa.types.Expression postconditions = 3;
      private java.util.List<boa.types.Ast.Expression> postconditions_ =
        java.util.Collections.emptyList();
      private void ensurePostconditionsIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          postconditions_ = new java.util.ArrayList<boa.types.Ast.Expression>(postconditions_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          boa.types.Ast.Expression, boa.types.Ast.Expression.Builder, boa.types.Ast.ExpressionOrBuilder> postconditionsBuilder_;

      /**
       * <code>repeated .boa.types.Expression postconditions = 3;</code>
       */
      public java.util.List<boa.types.Ast.Expression> getPostconditionsList() {
        if (postconditionsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(postconditions_);
        } else {
          return postconditionsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .boa.types.Expression postconditions = 3;</code>
       */
      public int getPostconditionsCount() {
        if (postconditionsBuilder_ == null) {
          return postconditions_.size();
        } else {
          return postconditionsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .boa.types.Expression postconditions = 3;</code>
       */
      public boa.types.Ast.Expression getPostconditions(int index) {
        if (postconditionsBuilder_ == null) {
          return postconditions_.get(index);
        } else {
          return postconditionsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .boa.types.Expression postconditions = 3;</code>
       */
      public Builder setPostconditions(
          int index, boa.types.Ast.Expression value) {
        if (postconditionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePostconditionsIsMutable();
          postconditions_.set(index, value);
          onChanged();
        } else {
          postconditionsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .boa.types.Expression postconditions = 3;</code>
       */
      public Builder setPostconditions(
          int index, boa.types.Ast.Expression.Builder builderForValue) {
        if (postconditionsBuilder_ == null) {
          ensurePostconditionsIsMutable();
          postconditions_.set(index, builderForValue.build());
          onChanged();
        } else {
          postconditionsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .boa.types.Expression postconditions = 3;</code>
       */
      public Builder addPostconditions(boa.types.Ast.Expression value) {
        if (postconditionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePostconditionsIsMutable();
          postconditions_.add(value);
          onChanged();
        } else {
          postconditionsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .boa.types.Expression postconditions = 3;</code>
       */
      public Builder addPostconditions(
          int index, boa.types.Ast.Expression value) {
        if (postconditionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePostconditionsIsMutable();
          postconditions_.add(index, value);
          onChanged();
        } else {
          postconditionsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .boa.types.Expression postconditions = 3;</code>
       */
      public Builder addPostconditions(
          boa.types.Ast.Expression.Builder builderForValue) {
        if (postconditionsBuilder_ == null) {
          ensurePostconditionsIsMutable();
          postconditions_.add(builderForValue.build());
          onChanged();
        } else {
          postconditionsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .boa.types.Expression postconditions = 3;</code>
       */
      public Builder addPostconditions(
          int index, boa.types.Ast.Expression.Builder builderForValue) {
        if (postconditionsBuilder_ == null) {
          ensurePostconditionsIsMutable();
          postconditions_.add(index, builderForValue.build());
          onChanged();
        } else {
          postconditionsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .boa.types.Expression postconditions = 3;</code>
       */
      public Builder addAllPostconditions(
          java.lang.Iterable<? extends boa.types.Ast.Expression> values) {
        if (postconditionsBuilder_ == null) {
          ensurePostconditionsIsMutable();
          super.addAll(values, postconditions_);
          onChanged();
        } else {
          postconditionsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .boa.types.Expression postconditions = 3;</code>
       */
      public Builder clearPostconditions() {
        if (postconditionsBuilder_ == null) {
          postconditions_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          postconditionsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .boa.types.Expression postconditions = 3;</code>
       */
      public Builder removePostconditions(int index) {
        if (postconditionsBuilder_ == null) {
          ensurePostconditionsIsMutable();
          postconditions_.remove(index);
          onChanged();
        } else {
          postconditionsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .boa.types.Expression postconditions = 3;</code>
       */
      public boa.types.Ast.Expression.Builder getPostconditionsBuilder(
          int index) {
        return getPostconditionsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .boa.types.Expression postconditions = 3;</code>
       */
      public boa.types.Ast.ExpressionOrBuilder getPostconditionsOrBuilder(
          int index) {
        if (postconditionsBuilder_ == null) {
          return postconditions_.get(index);  } else {
          return postconditionsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .boa.types.Expression postconditions = 3;</code>
       */
      public java.util.List<? extends boa.types.Ast.ExpressionOrBuilder> 
           getPostconditionsOrBuilderList() {
        if (postconditionsBuilder_ != null) {
          return postconditionsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(postconditions_);
        }
      }
      /**
       * <code>repeated .boa.types.Expression postconditions = 3;</code>
       */
      public boa.types.Ast.Expression.Builder addPostconditionsBuilder() {
        return getPostconditionsFieldBuilder().addBuilder(
            boa.types.Ast.Expression.getDefaultInstance());
      }
      /**
       * <code>repeated .boa.types.Expression postconditions = 3;</code>
       */
      public boa.types.Ast.Expression.Builder addPostconditionsBuilder(
          int index) {
        return getPostconditionsFieldBuilder().addBuilder(
            index, boa.types.Ast.Expression.getDefaultInstance());
      }
      /**
       * <code>repeated .boa.types.Expression postconditions = 3;</code>
       */
      public java.util.List<boa.types.Ast.Expression.Builder> 
           getPostconditionsBuilderList() {
        return getPostconditionsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          boa.types.Ast.Expression, boa.types.Ast.Expression.Builder, boa.types.Ast.ExpressionOrBuilder> 
          getPostconditionsFieldBuilder() {
        if (postconditionsBuilder_ == null) {
          postconditionsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              boa.types.Ast.Expression, boa.types.Ast.Expression.Builder, boa.types.Ast.ExpressionOrBuilder>(
                  postconditions_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          postconditions_ = null;
        }
        return postconditionsBuilder_;
      }

      // repeated string assignable_fields = 4;
      private com.google.protobuf.LazyStringList assignableFields_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureAssignableFieldsIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          assignableFields_ = new com.google.protobuf.LazyStringArrayList(assignableFields_);
          bitField0_ |= 0x00000008;
         }
      }
      /**
       * <code>repeated string assignable_fields = 4;</code>
       */
      public java.util.List<java.lang.String>
          getAssignableFieldsList() {
        return java.util.Collections.unmodifiableList(assignableFields_);
      }
      /**
       * <code>repeated string assignable_fields = 4;</code>
       */
      public int getAssignableFieldsCount() {
        return assignableFields_.size();
      }
      /**
       * <code>repeated string assignable_fields = 4;</code>
       */
      public java.lang.String getAssignableFields(int index) {
        return assignableFields_.get(index);
      }
      /**
       * <code>repeated string assignable_fields = 4;</code>
       */
      public com.google.protobuf.ByteString
          getAssignableFieldsBytes(int index) {
        return assignableFields_.getByteString(index);
      }
      /**
       * <code>repeated string assignable_fields = 4;</code>
       */
      public Builder setAssignableFields(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureAssignableFieldsIsMutable();
        assignableFields_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string assignable_fields = 4;</code>
       */
      public Builder addAssignableFields(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureAssignableFieldsIsMutable();
        assignableFields_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string assignable_fields = 4;</code>
       */
      public Builder addAllAssignableFields(
          java.lang.Iterable<java.lang.String> values) {
        ensureAssignableFieldsIsMutable();
        super.addAll(values, assignableFields_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string assignable_fields = 4;</code>
       */
      public Builder clearAssignableFields() {
        assignableFields_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string assignable_fields = 4;</code>
       */
      public Builder addAssignableFieldsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureAssignableFieldsIsMutable();
        assignableFields_.add(value);
        onChanged();
        return this;
      }

      // repeated string exception_types = 5;
      private com.google.protobuf.LazyStringList exceptionTypes_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureExceptionTypesIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          exceptionTypes_ = new com.google.protobuf.LazyStringArrayList(exceptionTypes_);
          bitField0_ |= 0x00000010;
         }
      }
      /**
       * <code>repeated string exception_types = 5;</code>
       */
      public java.util.List<java.lang.String>
          getExceptionTypesList() {
        return java.util.Collections.unmodifiableList(exceptionTypes_);
      }
      /**
       * <code>repeated string exception_types = 5;</code>
       */
      public int getExceptionTypesCount() {
        return exceptionTypes_.size();
      }
      /**
       * <code>repeated string exception_types = 5;</code>
       */
      public java.lang.String getExceptionTypes(int index) {
        return exceptionTypes_.get(index);
      }
      /**
       * <code>repeated string exception_types = 5;</code>
       */
      public com.google.protobuf.ByteString
          getExceptionTypesBytes(int index) {
        return exceptionTypes_.getByteString(index);
      }
      /**
       * <code>repeated string exception_types = 5;</code>
       */
      public Builder setExceptionTypes(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureExceptionTypesIsMutable();
        exceptionTypes_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string exception_types = 5;</code>
       */
      public Builder addExceptionTypes(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureExceptionTypesIsMutable();
        exceptionTypes_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string exception_types = 5;</code>
       */
      public Builder addAllExceptionTypes(
          java.lang.Iterable<java.lang.String> values) {
        ensureExceptionTypesIsMutable();
        super.addAll(values, exceptionTypes_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string exception_types = 5;</code>
       */
      public Builder clearExceptionTypes() {
        exceptionTypes_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string exception_types = 5;</code>
       */
      public Builder addExceptionTypesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureExceptionTypesIsMutable();
        exceptionTypes_.add(value);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:boa.types.Specification)
    }

    static {
      defaultInstance = new Specification(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:boa.types.Specification)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_boa_types_Specification_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_boa_types_Specification_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nspec.proto\022\tboa.types\032\tast.proto\"\270\001\n\rS" +
      "pecification\022\026\n\016is_exceptional\030\001 \002(\010\022,\n\r" +
      "preconditions\030\002 \003(\0132\025.boa.types.Expressi" +
      "on\022-\n\016postconditions\030\003 \003(\0132\025.boa.types.E" +
      "xpression\022\031\n\021assignable_fields\030\004 \003(\t\022\027\n\017" +
      "exception_types\030\005 \003(\tB\002H\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_boa_types_Specification_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_boa_types_Specification_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_boa_types_Specification_descriptor,
              new java.lang.String[] { "IsExceptional", "Preconditions", "Postconditions", "AssignableFields", "ExceptionTypes", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          boa.types.Ast.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
